/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thegpacalculator;

import java.awt.Color; //Importation of class Color from awt package.
import javax.swing.JOptionPane; //Importation of class JOptionPane from swing package.
import javax.swing.JTextField; //Importation of class JTextField from swing package.
import java.awt.Toolkit; //Importation of class Toolkit from awt package.
import java.awt.Dimension; //Importation of class Dimension from awt package.

/**
 *
 * @author jamil_sxi6i5q
 */
public class WelcomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome Screen");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255,80));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setText("         ");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Calculate GPA");

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        jButton1.setText("Start");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 280, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jamil_sxi6i5q\\Desktop\\360_F_361521180_mMN9HNjxBWBy4DV6nRqCgt23VtcFiscL.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int sumOfHours=0;//Declartion and initialization of sumOfHours variable.
    double sum=0.0;//Declartion and initialization of sum variable
    float GPA;//Only declartion for GPA variable .
    String numberOfSubjects;//Declartion of numberOfSubjects variable.
    int num1,num2;//Declartion of num1 and num2 variables.
    double num3;//Declartion of num3 variable.
    String numberOfHoursOfTheSubject;//Declartion of numberOfHoursOfTheSubject variable.
    String gradeOfTheSubject;//Declartion of gradeOfTheSubject variable.
    
    if("Start".equals(evt.getActionCommand()))//Conditional statement if.
    {
      JTextField textField1 = new JTextField(18);//Declartion and initialization of JTextField object (textField1).
      JTextField textField2 = new JTextField(18);//Declartion and initialization of JTextField object (textField2).
      JTextField textField3 = new JTextField(18);//Declartion and initialization of JTextField object (textField3).
        numberOfSubjects = JOptionPane.showInputDialog(textField1, "Please enter the number of registered subjects that you want to count in the GPA","Input Screen",JOptionPane.OK_CANCEL_OPTION);//JOptionPane declaring and initializing.
           num1 = Integer.parseInt(numberOfSubjects);//Changing the value of numberOfSubjects variable to int.
      Object[] Fields = {//Array of objects for multiple input dialog in the JOptionPane.
          "Number of hours of the subject",textField2,
          "Grade of the subject",textField3
      };
      for(int i=0;i<num1;i++)//For loop.
      {
       JOptionPane.showConfirmDialog(null,Fields,"Input Screen",JOptionPane.OK_CANCEL_OPTION);//JOptionPane declaring and initializing. 
       numberOfHoursOfTheSubject = textField2.getText();//Getting the string value of numberOfHoursOfTheSubject variable.
       num2 = Integer.parseInt(numberOfHoursOfTheSubject);//Changing the string value of numberOfHoursOfTheSubject variable to int value.
       gradeOfTheSubject = textField3.getText();//Getting the string value of gradeOfTheSubject variable.
       num3 = Double.parseDouble(gradeOfTheSubject);//Changing the string value of gradeOfTheSubject variable to int value.
       textField2.setText("");//Setting textField2 to empty field for avoiding showing inputs.
       textField3.setText("");//Setting textField3 to empty field for avoiding showing inputs.
        sum += (num2*num3);//Sum of multiplying numberOfHoursOfTheSubject(num2) & gradeOfTheSubject(num3).  
       sumOfHours+=num2;//Sum of total hours of all subjects.
      }
      GPA = (float) (sum/sumOfHours);//Initialization of GPA variable
      String caseDescription;//Declartion of some string variables.
       ResultScreen obj1 = new ResultScreen();//Declartion and initialization of ResultScreen object (obj1).
      if(GPA>=90) //Conditional statement if.
      {
          caseDescription = "               Excellent dear student";//Initialization of caseDescription variable.
          obj1.jLabel2.setText("               Congradulations");//Setting label2 text.
          obj1.jLabel2.setForeground(Color.BLUE);//Setting label2 text color.
          obj1.jLabel3.setText("            Your GPA = "+" "+GPA);//Setting label3 text.
          obj1.jLabel3.setForeground(Color.BLUE);//Setting label3 text color.
          obj1.jLabel4.setText(caseDescription);//Setting label4 text.
          obj1.jLabel4.setForeground(Color.BLUE);//Setting label4 text color.
          Toolkit toolkit = getToolkit();//Declartion and initialization of Toolkit object.
          Dimension size = toolkit.getScreenSize();//Declartion and initialization of Dimension object and set the screen size in it.
          obj1.setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);//Setting the frame in the center of the screen.
          obj1.setVisible(true);//Setting result screen visibility to true.
          
          
      }
      else if(GPA>=80&&GPA<90) //Conditional statement else if.
      {
          caseDescription = "              Very good dear student";//Initialization of caseDescription variable.
          obj1.jLabel2.setText("              Congradulations ");//Setting label2 text.
          obj1.jLabel2.setForeground(Color.BLUE);//Setting label2 text color.
          obj1.jLabel3.setText("           Your GPA = "+" "+GPA);//Setting label3 text.
          obj1.jLabel3.setForeground(Color.BLUE);//Setting label3 text color.
          obj1.jLabel4.setText(caseDescription);//Setting label4 text.
          obj1.jLabel4.setForeground(Color.BLUE);//Setting label4 text color.
          Toolkit toolkit = getToolkit();//Declartion and initialization of Toolkit object.
          Dimension size = toolkit.getScreenSize();//Declartion and initialization of Dimension object and set the screen size in it.
          obj1.setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);//Setting the frame in the center of the screen.
          obj1.setVisible(true);//Setting result screen visibility to true.
      }
      else if(GPA>=70&&GPA<80) //Conditional statement else if.
      {
          caseDescription = "                 Well done dear student";//Initialization of caseDescription variable.
          obj1.jLabel2.setText("                Congradulations ");//Setting label2 text.
          obj1.jLabel2.setForeground(Color.BLUE);//Setting label2 text color.
          obj1.jLabel3.setText("               Your GPA = "+" "+GPA);//Setting label3 text.
          obj1.jLabel3.setForeground(Color.BLUE);//Setting label3 text color.
          obj1.jLabel4.setText(caseDescription);//Setting label4 text.
          obj1.jLabel4.setForeground(Color.BLUE);//Setting label4 text color.
          Toolkit toolkit = getToolkit();//Declartion and initialization of Toolkit object.
          Dimension size = toolkit.getScreenSize();//Declartion and initialization of Dimension object and set the screen size in it.
          obj1.setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);//Setting the frame in the center of the screen.
          obj1.setVisible(true);//Setting result screen visibility to true.
      }
      else if(GPA>=60&&GPA<70) //Conditional statement else if.
      {
          caseDescription = "               Good dear student";//Initialization of caseDescription variable.
          obj1.jLabel2.setText("            Study Harder!! ");//Setting label2 text.
          obj1.jLabel2.setForeground(Color.RED);//Setting label2 text color.
          obj1.jLabel3.setText("            Your GPA = "+" "+GPA);//Setting label3 text.
          obj1.jLabel3.setForeground(Color.RED);//Setting label3 text color.
          obj1.jLabel4.setText(caseDescription);//Setting label4 text.
          obj1.jLabel4.setForeground(Color.RED);//Setting label4 text color.
          Toolkit toolkit = getToolkit();//Declartion and initialization of Toolkit object.
          Dimension size = toolkit.getScreenSize();//Declartion and initialization of Dimension object and set the screen size in it.
          obj1.setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);//Setting the frame in the center of the screen.
          obj1.setVisible(true);//Setting result screen visibility to true.
      }
      else //Conditional statement else.
      {
          caseDescription = "                 Not acceptable dear student";//Initialization of caseDescription variable.
          obj1.jLabel2.setText("            Study Harder And Harder!!");//Setting label2 text.
          obj1.jLabel2.setForeground(Color.RED);//Setting label2 text color.
          obj1.jLabel3.setText("                   Your GPA = "+" "+GPA);//Setting label3 text.
          obj1.jLabel3.setForeground(Color.RED);//Setting label3 text color.
          obj1.jLabel4.setText(caseDescription);//Setting label4 text.
          obj1.jLabel4.setForeground(Color.RED);//Setting label4 text color.
          Toolkit toolkit = getToolkit();//Declartion and initialization of Toolkit object.
          Dimension size = toolkit.getScreenSize();//Declartion and initialization of Dimension object and set the screen size in it.
          obj1.setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);//Setting the frame in the center of the screen.
          obj1.setVisible(true);//Setting result screen visibility to true.
      }
    }
      
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
